### ISSUE TITLE
Configurating .env file problem/question

### ISSUE THREAD

**Issue by GoTwin** [tomaszjagielka/ScrapyPy#1]
After filling these fields with correct data or maybe not it's showing that the inputed data is not correct
{
BACKPACK_CLIENT_ID="" #took steam id from backpack
BACKPACK_CLIENT_SECRET="" #took user id https://backpack.tf/connections generated token
}
Maybe I wrote somethins wrong, would be super nice if someone will explain me from where do I need take the data exactly from
If its somethins simple and i am missing smt don't be mad i am just beginner of coding on python..
My discord: GoTwin?#1281

**Comment by tomaszjagielka** [comment]
Thank you for reaching out. It seems that you might have misunderstood the purpose of the `BACKPACK_CLIENT_ID` and `BACKPACK_CLIENT_SECRET` fields. Sorry for the confusion.

The `BACKPACK_CLIENT_ID` and `BACKPACK_CLIENT_SECRET` fields are not related to your Steam ID or the token generated from the connections section of your backpack.tf account. Instead, they are unique identifiers for an app created on the backpack.tf website.

To use the program, please follow these steps:
1. Create an app on the backpack.tf website by following this link: https://backpack.tf/developer/apps.
2. Once you have created the app, you will be given a **Client ID** and a **Client Secret**. These credentials allow your application to access the backpack.tf API.
3. Input the **Client ID** into the `BACKPACK_CLIENT_ID` field, and the **Client Secret** into the `BACKPACK_CLIENT_SECRET` field in the **.env** file.
4. Make sure that you have set the `CREATE_ALERTS` flag  to `TRUE` in the **.env** file when running the program for the first time.
5. After running the program, please wait for a few moments for entries to show up.

If you have followed these steps and are still experiencing issues, please let me know and I will do my best to assist you further. Remember, everyone starts as a beginner, so don't hesitate to ask for help and continue learning.

**Comment by GoTwin** [comment]
Everything works, thanks!
